dealer/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path("", include("product.urls")),
    path('', include('django_prometheus.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("link", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

product/urls.py
from django.urls import path
from . import views
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *
from django.views.generic import TemplateView

app_name = 'core'

sitemaps = {
    'static': StaticViewSitemap,
    'product' : ProductSitemap,
    'blog' : NewsSitemap,
    'page' : PageSitemap,
}

urlpatterns = [
    path('', views.index, name='index'),
    path('produk/', views.product_list, name='product_list'),
    path('produk/<slug:slug>/', views.product_detail, name='product_detail'),
    path('berita/', views.news_list, name='news_list'),
    path('berita/<slug:slug>/', views.news_detail, name='news_detail'),
    path('hubungi-kami/', views.static_contact_us, name='static_contact_us'),
    path('halaman/<slug:slug>/', views.dynamic_page, name='dynamic_page'),
    path('whatsapp/', views.whatsapp, name='whatsapp'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name='robots'),
]

dealer/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en-US">

<head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="author" content="PT Claverio Data Pratama">
    <!-- Font Imports -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">

    <!-- Core Style -->
    <link rel="stylesheet" href="{% static 'dealer/style.css' %}">

    <!-- Font Icons -->
    <link rel="stylesheet" href="{% static 'dealer/css/font-icons.css' %}">
    <link rel="stylesheet" href="{% static 'dealer/demos/car/css/car-icons/style.css' %}">

    <!-- Plugins/Components CSS -->
    <link rel="stylesheet" href="{% static 'dealer/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'dealer/css/components/bs-select.css' %}">
    <link rel="stylesheet" href="{% static 'dealer/include/rs-plugin/css/settings.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'dealer/include/rs-plugin/css/layers.css' %}">
    <link rel="stylesheet" href="{% static 'dealer/include/rs-plugin/css/navigation.css' %}">

    <!-- Niche Demos -->
    <link rel="stylesheet" href="{% static 'dealer/demos/car/car.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'dealer/css/custom.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'link/images/favicon.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'link/images/favicon.png' %}">


    {% block custom_css %}

    {% endblock %}

    <!-- Document Title
	============================================= -->
    <title>{% block title %}{% endblock title %} - Denza Indonesia</title>

    <!-- Canonical Link -->
    <link rel="canonical"
          href="{% if request %}{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}"
          {% else %}https://www.denza-indonesia.id{% endif %}
    ">

    <!-- Meta Description -->
    <meta name="description" content="{% block meta_description %}{% endblock %}">

    <!-- Meta Keywords -->
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">

    <meta name="robots" content="index, follow">


    <!-- Open Graph (Facebook) Metadata -->
    <meta property="og:title" content="Indopesona - {% block og_title %}{% endblock %}">
    <meta property="og:description" content="{% block og_description %}{% endblock %}">
    <meta property="og:image" content="{% block meta_image %}{% endblock %}">
    <meta property="og:url"
          content="{% if request %}{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}"
          {% else %}https://www.indopesona.id{% endif %}
    ">
    <meta property="og:type" content="website">

<!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-11356917655"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'AW-11356917655');
    </script>


    <!-- Event snippet for Whatsapp conversion page
    In your html page, add the snippet and call gtag_report_conversion when someone clicks on the chosen link or button. -->
    <script>
        function gtag_report_conversion(url) {
        var callback = function () {
            if (typeof(url) != 'undefined') {
            window.location = url;
            }
        };
        gtag('event', 'conversion', {
            'send_to': 'AW-11356917655/Jzq8COP_2N0aEJefs6cq',
            'value': 2000.0,
            'currency': 'IDR',
            'event_callback': callback
        });
        return false;
        }
    </script>


    <style>
        /* Revolution Slider */
        .ares .tp-tab {
            border: 1px solid #eee;
        }

        .ares .tp-tab-content {
            margin-top: -4px;
        }

        .ares .tp-tab-content {
            padding: 15px 15px 15px 110px;
        }

        .ares .tp-tab-image {
            width: 80px;
            height: 80px;
        }
    </style>

</head>

<body class="stretched side-push-panel"
      data-loader-html="<div><img src='{% static 'dealer/demos/car/images/page-loader.gif' %}' alt='Loader'></div>">

<!-- Side Panel Overlay -->
<div class="body-overlay"></div>

<!-- Side Panel -->
<div id="side-panel">

    <div id="side-panel-trigger-close" class="side-panel-trigger"><a href="#"><i class="bi-x-lg"></i></a></div>

    <div class="side-panel-wrap">

        <div class="widget">

            <a href="#"><img src="{% static 'dealer/demos/car/images/denza/logo.png' %}" alt="Logo" height="50"></a>

        </div>

    </div>

</div>

<!-- Document Wrapper
============================================= -->
<div id="wrapper">

    {% include 'base/header.html' %}

    {% block content %}

    {% endblock %}

    <!-- Footer
    ============================================= -->
    {% include 'base/footer.html' %}
</div><!-- #wrapper end -->

<!-- Go To Top
============================================= -->
<div id="gotoTop" class="uil uil-angle-up"></div>

<!-- Contact Button
============================================= -->
<a href="{% url 'core:whatsapp' %}?{% if product_item %}product_id={{ product_item.id }}{% endif %}" target="_blank"  onclick="gtag_report_conversion()">
    <div id="contact-me" class="bi-whatsapp bg-whatsapp"></div>
</a>

<!-- JavaScripts
============================================= -->
<script src="{% static 'dealer/js/plugins.min.js' %}"></script>
<script src="{% static 'dealer/js/functions.bundle.js' %}"></script>
<script src="{% static 'dealer/demos/car/js/360rotator.js' %}"></script>

<!-- Bootstrap Select Plugin -->
<script src="{% static 'dealer/js/components/bs-select.js' %}"></script>

<!-- SLIDER REVOLUTION 5.x SCRIPTS  -->
<script src="{% static 'dealer/include/rs-plugin/js/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'dealer/include/rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script>

<script src="{% static 'dealer/include/rs-plugin/js/extensions/revolution.extension.actions.min.js' %}"></script>
<script src="{% static 'dealer/include/rs-plugin/js/extensions/revolution.extension.carousel.min.js' %}"></script>
<script src="{% static 'dealer/include/rs-plugin/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
<script src="{% static 'dealer/include/rs-plugin/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
<script src="{% static 'dealer/include/rs-plugin/js/extensions/revolution.extension.migration.min.js' %}"></script>
<script src="{% static 'dealer/include/rs-plugin/js/extensions/revolution.extension.navigation.min.js' %}"></script>
<script src="{% static 'dealer/include/rs-plugin/js/extensions/revolution.extension.parallax.min.js' %}"></script>
<script src="{% static 'dealer/include/rs-plugin/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
<script src="{% static 'dealer/include/rs-plugin/js/extensions/revolution.extension.video.min.js' %}"></script>


<script>

    //Car Appear In View
    function isScrolledIntoView(elem) {
        var docViewTop = jQuery(window).scrollTop();
        var docViewBottom = docViewTop + jQuery(window).height();

        var elemTop = jQuery(elem).offset().top + 180;
        var elemBottom = elemTop + jQuery(elem).height() - 500;

        return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
    }

    jQuery(window).scroll(function () {
        jQuery('.running-car').each(function () {
            if (isScrolledIntoView(this) === true) {
                jQuery(this).addClass('in-view');
            } else {
                jQuery(this).removeClass('in-view');
            }
        });
    });

    //threesixty degree
    window.onload = init;
    var car;

    function init() {

        car = jQuery('.360-car').ThreeSixty({
            totalFrames: 52, // Total no. of image you have for 360 slider
            endFrame: 52, // end frame for the auto spin animation
            currentFrame: 3, // This the start frame for auto spin
            imgList: '.threesixty_images', // selector for image list
            progress: '.spinner', // selector to show the loading progress
            imagePath: 'demos/car/images/360degree-cars/', // path of the image assets
            filePrefix: '', // file prefix if any
            ext: '.png', // extention for the assets
            height: 887,
            width: 500,
            navigation: true,
            responsive: true,
        });
    };

    // Rev Slider
    var revapi424, tpj = jQuery;
    tpj(document).ready(function () {
        if (tpj("#rev_slider_424_1").revolution == undefined) {
            revslider_showDoubleJqueryError("#rev_slider_424_1");
        } else {
            revapi424 = tpj("#rev_slider_424_1").show().revolution({
                sliderType: "carousel",
                jsFileLocation: "include/rs-plugin/js/",
                sliderLayout: "auto",
                dottedOverlay: "none",
                delay: 7000,
                navigation: {
                    keyboardNavigation: "off",
                    keyboard_direction: "horizontal",
                    mouseScrollNavigation: "off",
                    mouseScrollReverse: "default",
                    onHoverStop: "off",
                    touch: {
                        touchenabled: "on",
                        swipe_threshold: 75,
                        swipe_min_touches: 1,
                        swipe_direction: "horizontal",
                        drag_block_vertical: false
                    }
                    ,
                    arrows: {
                        style: "uranus",
                        enable: false,
                        hide_onmobile: false,
                        hide_onleave: true,
                        hide_delay: 200,
                        hide_delay_mobile: 1200,
                        tmp: '',
                        left: {
                            h_align: "left",
                            v_align: "center",
                            h_offset: -10,
                            v_offset: 0
                        },
                        right: {
                            h_align: "right",
                            v_align: "center",
                            h_offset: -10,
                            v_offset: 0
                        }
                    },
                    carousel: {
                        maxRotation: 65,
                        vary_rotation: "on",
                        minScale: 55,
                        vary_scale: "on",
                        horizontal_align: "center",
                        vertical_align: "center",
                        fadeout: "on",
                        vary_fade: "on",
                        maxVisibleItems: 5,
                        infinity: "off",
                        space: 0,
                        stretch: "on"
                    }
                    ,
                    tabs: {
                        style: "ares",
                        enable: true,
                        width: 270,
                        height: 80,
                        min_width: 270,
                        wrapper_padding: 10,
                        wrapper_color: "transparent",
                        wrapper_opacity: "0.5",
                        tmp: '<div class="tp-tab-content">  <span class="tp-tab-date">{{param1}}</span>  <span class="tp-tab-title">{{title}}</span></div><div class="tp-tab-image"></div>',
                        visibleAmount: 7,
                        hide_onmobile: false,
                        hide_under: 420,
                        hide_onleave: false,
                        hide_delay_mobile: 1200,
                        hide_delay: 200,
                        direction: "horizontal",
                        span: true,
                        position: "outer-bottom",
                        space: 20,
                        h_align: "left",
                        v_align: "bottom",
                        h_offset: 0,
                        v_offset: 0
                    }
                },
                visibilityLevels: [1240, 1024, 778, 480],
                gridwidth: [1240, 992, 768, 420],
                gridheight: [600, 500, 960, 720],
                lazyType: "single",
                shadow: 0,
                spinner: "off",
                stopLoop: "off",
                stopAfterLoops: 0,
                stopAtSlide: 1,
                shuffle: "off",
                autoHeight: "off",
                hideThumbsOnMobile: "off",
                hideSliderAtLimit: 0,
                hideCaptionAtLimit: 0,
                hideAllCaptionAtLilmit: 0,
                debugMode: false,
                fallbacks: {
                    simplifyAll: "off",
                    nextSlideOnWindowFocus: "off",
                    disableFocusListener: false,
                }
            });
        }
    });	/*ready*/

    // Video on play on hover
    jQuery(document).ready(function ($) {
        jQuery('.videoplay-on-hover').hover(function () {
            if (jQuery(this).find('video').length > 0) {
                jQuery(this).find('video').get(0).play();
            }
        }, function () {
            if (jQuery(this).find('video').length > 0) {
                jQuery(this).find('video').get(0).pause();
            }
        });
    });
</script>



</body>

</html>

dealer/templates/base/footer.html
{% load static %}

<footer id="footer" class="dark border-0" style="background-color: #e6e6e6;">
    <div class="container-fluid px-5">
        <!-- Footer Widgets
        ============================================= -->
        <div class="footer-widgets-wrap">

            <div class="row col-mb-50 justify-content-between">
                <div class="col-lg-7">

                    <div class="row col-mb-30">
                        <div class="col-6 col-lg-3">
                            <div class="widget widget_links widget-li-noicon">
                                <h4 class="text-black">Media Sosial</h4>
                                <ul>
                                    {% if settings.globalsetting.SocialSetting.instagram_link %}
                                        <li><a href="{{ settings.globalsetting.SocialSetting.instagram_link }}" target="_blank">Instagram</a>
                                        </li>
                                    {% endif %}
                                    {% if settings.globalsetting.SocialSetting.tiktok_link %}
                                        <li><a href="{{ settings.globalsetting.SocialSetting.tiktok_link }}" target="_blank">Tiktok</a></li>
                                    {% endif %}
                                    {% if settings.globalsetting.SocialSetting.youtube_link %}
                                        <li><a href="{{ settings.globalsetting.SocialSetting.youtube_link }}" target="_blank">Youtube</a></li>
                                    {% endif %}
                                    {% if settings.globalsetting.SocialSetting.facebook_link %}
                                        <li><a href="{{ settings.globalsetting.SocialSetting.facebook_link }}" target="_blank">Facebook</a>
                                        </li>
                                    {% endif %}
                                    {% if settings.globalsetting.SocialSetting.linkedin_link %}
                                        <li><a href="{{ settings.globalsetting.SocialSetting.linkedin_link }}" target="_blank">Linkedin</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="widget widget_links widget-li-noicon">
                                <h4 class="text-black">Produk</h4>
                                <ul>
                                    {% for product in ctx_products %}
                                        <li><a href="{{ product.get_url }}">{{ product.title|truncatechars:25 }}</a>
                                        </li>
                                    {% endfor %}

                                </ul>
                            </div>
                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="widget widget_links widget-li-noicon">
                                <h4 class="text-black">Berita dan Blog</h4>
                                <ul>
                                    {% for news in ctx_latest_news %}
                                        <li><a href="{{ news.get_url }}">{{ news.title|truncatechars:25 }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="widget widget_links widget-li-noicon">
                                <h4 class="text-black">Halaman</h4>
                                <ul>
                                    {% for page in ctx_misc_pages %}
                                        <li><a href="{{ page.get_url }}">{{ page.title }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-lg-5 text-center text-lg-end">
                    <img src="{% static 'dealer/demos/car/images/denza/logo.png' %}" alt="Image" height="50">
                </div>
            </div>

        </div><!-- .footer-widgets-wrap end -->
    </div>
</footer><!-- #footer end -->

dealer/templates/base/header.html
{% load static %}

<!-- Header
============================================= -->
<header id="header" class="full-header header-size-custom" data-sticky-shrink="false">
    <div id="header-wrap">
        <div class="container-fluid">
            <div class="header-row flex-lg-row-reverse">

                <!-- Logo
                ============================================= -->
                <div id="logo" class="me-lg-0 ms-lg-auto" style="padding-top: 5px; padding-bottom: 5px;">
                    <a href="{% url 'core:index' %}">
                        <img class="logo-default"
                             srcset="{% static 'dealer/demos/car/images/denza/logo.png' %}, {% static 'dealer/demos/car/images/denza/logo.png' %}"
                             src="{% static 'dealer/demos/car/images/denza/logo.png' %}" alt="Logo" height="50"
                             width="230"
                             style="transform: scale(0.85); transform-origin: center;">
                    </a>
                </div>

                <!-- #logo end -->

                <div class="primary-menu-trigger">
                    <button class="cnvs-hamburger" type="button" title="Open Mobile Menu">
                        <span class="cnvs-hamburger-box"><span class="cnvs-hamburger-inner"></span></span>
                    </button>
                </div>

                <!-- Primary Navigation
                ============================================= -->
                <nav class="primary-menu with-arrows">
                    <ul class="menu-container">
                        <li class="menu-item current"><a class="menu-link" href="{% url 'core:index' %}">
                            <div>Beranda</div>
                        </a></li>
                        <!-- Mega Menu -->
                        <li class="menu-item mega-menu"><a class="menu-link" href="{% url 'core:product_list' %}">
                            <div>Produk</div>
                        </a>
                            <div class="mega-menu-content mega-menu-style-2">
                                <div class="container">
                                    <div class="row">
                                        <ul class="sub-menu-container mega-menu-column col-12">
                                            <li class="menu-item">
                                                <div class="widget text-center">

                                                    <h3 class="mb-0">Denza Indonesia</h3>
                                                    <a href="{% url 'core:product_list' %}"
                                                       class="button button-small button-rounded button-border button-dark button-black font-primary"
                                                       style="margin: 10px 0 40px">Lihat Semua Produk</a>

                                                    <!-- Mega Menu Cars Carousel -->
                                                    <div class="owl-carousel image-carousel carousel-widget text-center"
                                                         data-margin="20" data-nav="false" data-pagi="true"
                                                         data-items-xs="1" data-items-sm="2" data-items-md="4"
                                                         data-items-lg="6" data-items-xl="6">
                                                        {% for product in ctx_products %}
                                                        <div class="oc-item"><a href="{{ product.get_url }}"><img
                                                                src="{{ product.image_trans_header.url }}"
                                                                alt="Car">{{ product.title }}</a></div>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="{% url 'core:news_list' %}">
                            <div>Berita</div>
                        </a>
                        </li>
                        <li class="menu-item sub-menu">
                            <a class="menu-link"><div>Halaman<i class="sub-menu-indicator fa-solid fa-caret-down"></i></div></a>
                            <ul class="sub-menu-container d-none" style="">
                                {% for page in ctx_misc_pages %}
                                    <li class="menu-item current"><a class="menu-link" href="{{ page.get_url }}">
                                        <div>{{ page.title }}</div>
                                    </a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </nav><!-- #primary-menu end -->

            </div>
        </div>
    </div>
    <div class="header-wrap-clone"></div>
</header><!-- #header end -->